### ISSUE TITLE
Avoid recompiling `gmp` twice

### ISSUE THREAD

**Issue by samoht** [mirage/mirage-dev#59]
Would be nice to use the system gmp for the unix installation. On the cubi it takes ages to compile, so doing that twice is not very user-friendly.

**Comment by hannesm** [comment]
I asked https://github.com/ocaml/opam/issues/2074 whether `depopts` can in the future contain formulas. (certainly there are other hackish ways to achieve this goal, but I think that `depopts` have formulas makes sense in the broader picture)

**Comment by hannesm** [comment]
I believe this can be closed now..
